server:
  port: 8082

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      routes:
        - id: iot-platform
          uri: lb://IOT-PLATFORM
          predicates:
            - Path=/iot/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"