server:
  port: 8081

spring:
  application:
    name: iot-platform

message: Hello from Spring Cloud Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
