apiVersion: v1
kind: Service
metadata:
  name: iot-platform
  namespace: devops

spec:
  selector:
    app: iot-platform

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

  type: NodePort